### ISSUE TITLE
Specify a default path for each exercise

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/learn.svelte.dev#119]
On some exercises it would be nice if we could skip to a particular page, rather than assuming `/`

**Comment by dummdidumm** [comment]
Which exercises would benefit from that?

**Comment by Rich-Harris** [comment]
https://learn.svelte.dev/tutorial/page-data would benefit from starting on `/blog`, for example. (We could alternatively just move the blog to the root route, but then it's less clear what it is). Similarly, https://learn.svelte.dev/tutorial/param-matchers could start on `/colors/ff3e00`. We could achieve this with redirects — that's what happens on https://learn.svelte.dev/tutorial/invalidation — but it adds unnecessary stuff to the example
