### ISSUE TITLE
Error on "Part1/Bindings/Textarea inputs" tutorial

### ISSUE THREAD

**Issue by BeeMargarida** [sveltejs/learn.svelte.dev#141]
The tutorial looks great!

However, this error appears when accessing https://learn.svelte.dev/tutorial/textarea-inputs. Similar error for the `/context-api` tutorial as well

![image](https://user-images.githubusercontent.com/25725586/207682674-80ec008a-1f82-4baf-9002-c1d7a2e705e7.png)

The dependency is in package.json, some problem in the deploy perhaps?

**Comment by dummdidumm** [comment]
Thanks for noticing! It's the same underlying reason as #124, we need to think of a good solution for this.

**Comment by Rich-Harris** [comment]
this was fixed at some point, by adding `marked` to the section's `node_modules`
