### ISSUE TITLE
Dark mode scrollbar on Chromium based browser on Windows

### ISSUE THREAD

**Issue by mustofa-id** [sveltejs/learn.svelte.dev#142]
Chrome, Brave, Edge

![image](https://user-images.githubusercontent.com/25121822/207747039-dc5d5e17-e508-4ea7-8147-a4433740fc1b.png)

Adding `color-scheme: dark` in `@media (prefers-color-scheme: dark)
:root { ... }` seems fix this

![image](https://user-images.githubusercontent.com/25121822/207747652-c919a044-5576-4fc5-a2fc-ad5535c94238.png)

**Comment by dummdidumm** [comment]
We should probably do the same as https://github.com/sveltejs/kit/pull/8044
