### ISSUE TITLE
Text input focus sometimes lost on rerender/error

### ISSUE THREAD

**Issue by henrikvilhelmberglund** [sveltejs/learn.svelte.dev#150]
Just typing I find the text input focus is lost randomly which makes typing difficult. The following gif is from https://learn.svelte.dev/tutorial/your-first-component

![focus](https://user-images.githubusercontent.com/110549389/207898195-93be8602-75e9-4021-8cb9-53d8fc3b00fe.gif)

This seems like a problem because I'm writing the script tag and end tag before the contents of it, is that something I shouldn't do?

**Comment by dummdidumm** [comment]
I believe it's SvelteKit's "reset focus" action which causes this. Not sure yet how to best counteract it.
