### ISSUE TITLE
Why the complicated setup with webcontainer and stackblitz and third party cookies

### ISSUE THREAD

**Issue by gitter-me** [sveltejs/learn.svelte.dev#151]
First of all I really appreciate the effort going into the new learning section.

For me svelte stands for a lean and fast framework, but the new output area is the complete opposite of that.

I experience the same issues like other people here (e.g https://github.com/sveltejs/learn.svelte.dev/issues/99)
The output area requires multiple external requests to stackblitz.com, staticblitz.com and webcontainer.io (plus webassembly / web workers) with downloading a large amount of data.

Even when it works it takes a long time to spin up, and also my fans are spinning during the loading.
The old tutorial (https://svelte.dev/tutorial) is ready in seconds (it used unpkg.com).

If we want new people to get excited about svelte, this has to be as smooth and fast as it possibly could be.

And guiding users to turn off browser (privacy) security settings, like turn off the 3p cookies protection, is in my opinion the complete wrong way.

If I'd been a new user of svelte and wanted to get started with, my journey would have ended already here.

I understand that the new learning section also covers sveltekit with requires server-side stuff, but is this the only solution? (or perhaps the same base as the old tutorial section could be used)

**Comment by Conduitry** [comment]
It's likely to be the only solution for the time being. It's entirely impractical for us for now to make SvelteKit run in the browser without having Node run in the browser.

**Comment by osamakhn** [comment]
can we proxy stackblitz scripts for webcontainer so they are served from svelte dns? this will bypass tracking issues and most probably work fine on stackblitz side of things. happy to help do this

**Comment by Rich-Harris** [comment]
I'm pretty sure those external URLs are hardcoded in various places, so proxying wouldn't do much good. I'll close this as there isn't really a good alternative right now
