### ISSUE TITLE
Whitespace changes width when text is selected in the editor

### ISSUE THREAD

**Issue by Zokalyx** [sveltejs/learn.svelte.dev#164]
# Description
Selecting text on the editor renders the same text but space is shortened significantly.

# Steps to reproduce
- Go to [https://learn.svelte.dev/tutorial/your-first-component](https://learn.svelte.dev/tutorial/your-first-component)
- Select/highlight the only line in the editor
- `<h1>Hello world!</h1>` becomes text that reads as `<h1>Helloworld!</h1>` when highlighted (the whitespace is still there)

Reproduced in Google Chrome with no modifications. Version 108.0.5359.125 (Official Build) (64-bit).

# Example
![image](https://user-images.githubusercontent.com/36007346/208539541-4a0b7d3c-4a41-4dc1-92d3-7c17c8b5a7d5.png)
![image](https://user-images.githubusercontent.com/36007346/208539594-27682910-4df9-4663-a86f-ace9e8eff6a4.png)

**Comment by tomoam** [comment]
It seems that we need to invoke `monaco.editor.remeasureFonts()` after the custom fonts are available.

https://github.com/microsoft/monaco-editor/issues/648#issuecomment-564978560
