### ISSUE TITLE
Part 1 / Lifecycle / beforeUpdate and afterUpdate: "runScript Failed to run `dev`. Script is missing."

### ISSUE THREAD

**Issue by Wolfram-Zell** [sveltejs/learn.svelte.dev#178]
https://learn.svelte.dev/tutorial/update

The preview does not load and the console errors:
"index-dbfff98c.js:1 [dev] ERR!: runScript Failed to run `dev`. Script is missing."

**Comment by tillschander** [comment]
I can confirm the issue. Other tutorials up to this one work fine.

**Comment by dr-noid** [comment]
Happens to me too on this exact page.
