### ISSUE TITLE
Error on "Part 1/Lifecycle/beforeUpdate and afterUpdate"

### ISSUE THREAD

**Issue by mattelim** [sveltejs/learn.svelte.dev#179]
## URL
https://svelte.dev/tutorial/update

## Issue
The code snippet on the left pane includes this part:
```
beforeUpdate(() => {
	autoscroll = div && (div.offsetHeight + div.scrollTop) > (div.scrollHeight - 20);
});
```
The autoscroll calculation is wrong, it should be replaced with:
`autoscroll = div && (div.offsetHeight + div.scrollTop) < (div.scrollHeight + 20);`

## Screenshots
To replicate, scroll to the top of the chat div.

Before fix (does not scroll down after user input):
![error](https://user-images.githubusercontent.com/17747414/210469125-8a1376fb-f829-43ea-ae21-9a88596bd1c1.gif)

After fix (scrolls down after user input):
![ok](https://user-images.githubusercontent.com/17747414/210470089-be3f0713-b1c7-4301-bb5f-cb92e9b5d254.gif)

**Comment by Rich-Harris** [comment]
The code is correct. It's not _supposed_ to scroll down if you've scrolled backwards in the chat, because that would be annoying — it only autoscrolls if you're within 20px of the bottom. This is how basically all chat interfaces work. With the proposed change, `autoscroll` would always be `true`
