### ISSUE TITLE
03-reactive-statements console.log()

### ISSUE THREAD

**Issue by royhutw** [sveltejs/learn.svelte.dev#196]
console.log(`the count is ${count}`);
It does not work properly on localhost.

It should be:
$: count, console.log(`the count is ${count}`);

PS. Sorry for my poor English.

**Comment by dummdidumm** [comment]
Both work, so `$: console.log(..)` is the more concise solution. I'm not sure what you mean by "does not work properly on localhost"?

**Comment by royhutw** [comment]
Thanks for your relpy. I misunderstood.
