### ISSUE TITLE
Improvement in Stores / Readable stores tutorial

### ISSUE THREAD

**Issue by safwansamsudeen** [sveltejs/learn.svelte.dev#199]
In the [Readable stores tutorial](https://learn.svelte.dev/tutorial/readable-stores), this is the current code which is the valid answer:
```js
export const time = readable(new Date(), function start(set) {
	const interval = setInterval(() => {
		set(new Date());
	}, 1000);

	return function stop() {
		clearInterval(interval);
	};
});
```
Both the `start` and `stop` functions need not have a name, as is the case here. As there is a name, beginners might mistakenly continue to use this, which might be bad practice, as it's unnecessary code and declares variables, using memory inefficiently. I suggest using anonymous functions:
```js
export const time = readable(new Date(), (set) => {
	const interval = setInterval(() => {
		set(new Date())
        }, 1000)
	return () => {
		clearInterval(interval)
	};
});
```
 This change also improves consistency, as in most (all, to my observation) other places in the tutorial, anonymous functions are used when the function is not called more than once. A good example might be in the lifecycle tutorials: all the functions passed into the lifecycle functions are anonymous. 

We could improve it even more to make them one lined, again improving simplicity and consistency:
```js
export const time = readable(new Date(), (set) => {
	const interval = setInterval(() => set(new Date()), 1000)
	return () => clearInterval(interval);
});
```

**Comment by safwansamsudeen** [comment]
This also applies to the next tutorial: Derived stores. Here, it's even worse, as there is also a constant named `start`. So we have both a function and a constant named `start`. While this is allowed in JS in these circumstances, it's definitely not good practice.

**Comment by dummdidumm** [comment]
It's written that way so people know what function has which purpose. This outweighs the theoretical performance cost. Since lambda functions are used in many other places, I'd argue this is ok in this case. Therefore closing this.
