### ISSUE TITLE
Eliza chatbot appears to work fine on https://learn.svelte.dev/tutorial/update, despite message saying it doesn't work

### ISSUE THREAD

**Issue by leothorp** [sveltejs/learn.svelte.dev#236]
At https://learn.svelte.dev/tutorial/update, there is currently the message
```
The Eliza Chatbot in this exercise doesn't currently work. For now, you can use the old tutorial instead: https://svelte.dev/tutorial/update. 
```

However I'm seeing it as working fine (macOS Chrome, Version 110.0.5481.177)- the chatbot responds, and scrolling works as expected once the exercise is solved. 

Should that warning be removed now? I can make a PR if so.

**Comment by dummdidumm** [comment]
Ah yes, this is outdated - PR welcome!
