### ISSUE TITLE
Links don't look like a link when used inside a code line

### ISSUE THREAD

**Issue by nicholascostadev** [sveltejs/learn.svelte.dev#238]
I've noticed that whenever a link is used inside backticks in markdown, it's hard to know if it's a link and I don't know if that's intentional

[Example](https://learn.svelte.dev/tutorial/prerender):
![image](https://user-images.githubusercontent.com/86835927/224009477-25b1c0c7-c648-426f-bf9a-032b0dbc38f9.png)
![image](https://user-images.githubusercontent.com/86835927/224009591-10ff4fb6-58cc-4e91-9f9d-d96a1ce7fd18.png)

There is no way to know it's a link unless you hover over it, maybe slightly change the styling of it should be better?

**Comment by Rich-Harris** [comment]
thanks!
