### ISSUE TITLE
exercises that are broken

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/learn.svelte.dev#282]
starting a list:

* [ ] context API

**Comment by marksteven** [comment]
Hi Rich,
Not sure if it is me but think this exercise (for me at least) appears broken.
https://learn.svelte.dev/tutorial/params
Add [blog] and then attempt to add +page.svelte and throws error.
Hope that helps.
Great tutorial by the way

**Comment by Rich-Harris** [comment]
What error is being thrown? Are you creating `[slug]` as a file rather than a directory? If so, we should catch that and prevent the file from being created

**Comment by marksteven** [comment]
Thanks for getting back to me.
Using the "solve" I could see what it was supposed to be but how I did it threw errors.
clicking after fresh reload on blog you are given 2 options folder and page.
I clicked on folder and made [slug] folder then attempted to navigate in and then make +page.svelte which of course threw error as site tried to make one one folder up where there was one already.

Finally worked out what is meant to happen is start on blog
click on new folder and type in one line
[slug]/+page.svelte
enter and it works by adding a folder and file
But its not so obvious that is what you have to do.
I usually make a folder first navigate into it and then make a file so guessing others do the same.
So not sure how to explain it better than you already have.
But you might have some ideas.
Hope this helps you.
Cheers
Mark

**Comment by Rich-Harris** [comment]
Can you make a screen recording? Because this works fine:

https://user-images.githubusercontent.com/1162160/227245705-d1b7b940-5e90-488c-982c-5350c25a9f8f.mov

**Comment by Rich-Harris** [comment]
> Are you creating `[slug]` as a file rather than a directory?

If it's this, the error will be caught by #296:

https://learn-svelte-dev-git-disallow-file-as-directory-svelte.vercel.app/tutorial/params

**Comment by marksteven** [comment]
![Screen Shot 2023-03-23 at 22 04 45](https://user-images.githubusercontent.com/3622273/227453349-7a9d32e5-8bbf-40d7-baef-a8a84f722422.jpg)
Have attempted to replicate the error to make you a video but now cannot as it does exactly as your video does and if you do it wrong, even on purpose, you get the  correct error messages. So I am now not sure how I broke it. Sorry to waste your time.

**Comment by Rich-Harris** [comment]
cool — have merged #296, and this issue is covered by #293 so i'll close this
