### ISSUE TITLE
updating dependencies fails

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/learn.svelte.dev#297]
Going from https://learn.svelte.dev/tutorial/textarea-inputs forward to https://learn.svelte.dev/tutorial/update causes this error:

<img width="942" alt="image" src="https://user-images.githubusercontent.com/1162160/227279455-cf0be0f7-167b-40dc-aa2c-af7aaf7dca6a.png">

Not 100% sure what that means, but I feel like this might be relevant: https://github.com/sveltejs/learn.svelte.dev/blob/f0bcb33245579ab48e82e8bde54ed92a1a895409/src/lib/client/adapters/webcontainer/index.js#L139-L141

**Comment by tomoam** [comment]
@Rich-Harris 

> Not 100% sure what that means, but I feel like this might be relevant

It’s exactly as you said. The code is intended to prevent the deletion of common dependencies like `@sveltejs/kit` and `esbuild` located in the `node_modules` directory, but I found that it should also prevent each exercise-specific dependencies from being deleted. These dependencies are needed until Vite's HMR is finished.

If exercise-specific dependencies are not deleted, they will remain in the node_modules directory even when we switch to another exercise, but I don't think this will cause any issues. There is an idea to fix it, which would programmatically restart the vite, but it seems to slow down the switching between exercises a little bit.

I will submit a PR.
