### ISSUE TITLE
SvelteKit Routing Group Tutorial defect

### ISSUE THREAD

**Issue by pafech** [sveltejs/learn.svelte.dev#311]
# Problem
The Svelte Kit Routing Group Tutorial doesn't work correctly.

# Steps to reproduce
* Visit Page https://learn.svelte.dev/tutorial/route-groups
* Click "solve"
* In dev container, click on "account"
* Click "log in"

# Expected behavior
* account page under (authed) is shown

# Actual behavior
* an error message is shown `405 POST method not allowed. No actions exist for this page`

# Seed
*  https://github.com/sveltejs/learn.svelte.dev/tree/main/content/tutorial/04-advanced-sveltekit/03-advanced-routing/04-route-groups

# Screenshot
![issue](https://user-images.githubusercontent.com/16943993/229621249-f6d72b2a-4051-4ea0-945e-7f973e05aa61.png)

**Comment by dummdidumm** [comment]
Probably needs to turn of CSFR protection or sth like that since it's in the web container

**Comment by tomoam** [comment]
Perhaps replacing the HTTP Status Code from `307` to `303` (or `302`) will fix it. I will submit a PR.

**Comment by Rich-Harris** [comment]
thanks for the report!
