### ISSUE TITLE
Pop-out window

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/learn.svelte.dev#313]
Very occasionally it's nice to be able to view the output in a separate window/tab. Might be cool to have a button to open one, rather than digging around in the DOM to find the URL

**Comment by tomoam** [comment]
I very much agree.
I think this could be implemented by adding something like:

```svelte
<a href={$base + path} target="_blank">Open in New Tab</a>
```
...but would need to be carefully tested for errors, etc.

I will create a draft PR to share and discuss the idea.

**Comment by Rich-Harris** [comment]
closed via #329
