### ISSUE TITLE
"Rest parameters" exercise has a blank display

### ISSUE THREAD

**Issue by tomoam** [sveltejs/learn.svelte.dev#321]
https://learn.svelte.dev/tutorial/rest-params

This is because `content/tutorial/common/src/routes/+page.svelte` exists.

<img width="1128" alt="image" src="https://user-images.githubusercontent.com/29677552/230078375-8abc3b18-3758-4ab6-b745-a124df1026de.png">

**Comment by Rich-Harris** [comment]
closed via 81eb254dab39f4e7290d56ad9c54a9942d83b95b

**Comment by tomoam** [comment]
thank you!
