### ISSUE TITLE
losing focus when accepting autocompletions

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/learn.svelte.dev#324]
Not every time, but sometimes:

https://user-images.githubusercontent.com/1162160/230167246-5dbff2f7-994c-42c1-b178-bfb48b012dc0.mov

**Comment by tomoam** [comment]
This might be fixed by setting `closeOnBlur` to `false`.
https://codemirror.net/docs/ref/#autocomplete.autocompletion^config.closeOnBlur

**Comment by tomoam** [comment]
Occurs when accepting autocompletions by Tab key, but not by Enter key.
Perhapes because of the following code.

https://github.com/sveltejs/learn.svelte.dev/blob/b0e2f6e5c0325cbc9306e212fe0778abba6bd0dc/src/routes/tutorial/%5Bslug%5D/Editor.svelte#L209-L217
