### ISSUE TITLE
iframe sometimes gets disconnected

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/learn.svelte.dev#335]
Unfortunately I think #309 has made the site less robust — I'll occasionally run into blank pages that don't recover. It's hard to reproduce, but I've seen it a number of times.

If we don't reinstate the same behaviour we had before, I wonder if there's something smart we could do with e.g. `unload` events to track whether or not we're currently connected to the iframe (e.g. if the iframe was unloaded, making an edit should forcibly refresh it)

**Comment by tomoam** [comment]
@Rich-Harris 
Is what you saw a completely blank page or a default error page like `500 | Internal Error`?

If it is the default error page, I have seen it too, and it seems to happen most often when the browser's developer tools are open. If the Developer Tools are in a closed state, it seems to recover automatically. (Of course, I still think we should fix it).

I have never seen a completely blank page, but if you have, please let me know. It might give us a clue.

I will tackle this, but it will probably take a while. If you need a fix sooner to prepare for your Front End Master Course next week, let me know and I will revert #309 first.
(I watched the Dev Vlog. This is off-topic, but thanks for mentioning me, I'm very happy😊).

**Comment by Rich-Harris** [comment]
I've seen completely blank pages that require clicking the reload icon. If I manage to figure out a way to reproduce it consistently I'll update this issue. 

> This is off-topic, but thanks for mentioning me, I'm very happy😊

Yeah! Your contributions to the project have been awesome and very much appreciated

**Comment by Rich-Harris** [comment]
Just realised that we also don't refresh the page if the fallback error page is shown (as in https://learn.svelte.dev/tutorial/fallback-errors). The approach above might fix that

**Comment by tomoam** [comment]
In the case of fallback errors, reloading the iframe might cause flash in dark mode.
How about automatically inserting `__client.js` in `/src/error.html` as in `/src/app.html`?

**Comment by Rich-Harris** [comment]
great idea! that'll definitely help in the fallback error case. opened #343

**Comment by Rich-Harris** [comment]
merged #345 so i'll close this and hope the issue doesn't reappear in another form

**Comment by login6** [comment]
> merged #345 so i'll close this and hope the issue doesn't reappear in another form

I have this issue constantly. About each third or second time when i open the site. Just blank page, no rendering svelte files. Only reload helps. Debian stable, last chromium. I think something deeply wrong there.
