### ISSUE TITLE
Race condition when restarting server

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/learn.svelte.dev#341]
Not quite sure what's going on here, but rapidly editing an `.env` file seems to cause something to get stuck:

https://learn.svelte.dev/tutorial/env-static-public

https://user-images.githubusercontent.com/1162160/230727682-285d9739-7292-42d8-858a-fe20a5a55ddb.mov

**Comment by tomoam** [comment]
Vite restarts on `.env` file update. 
https://github.com/vitejs/vite/blob/09350c69ada6a43b26241b99a0d4f8aa4283ade2/packages/vite/src/node/server/hmr.ts#L44-L75

So we might have to wait for `server-ready` when updating the `.env` file as well.

**Comment by tomoam** [comment]
I agree completely.
I tried to implement waiting for `server-ready` in the `update` method when updating `.env` and found out why that mechanism is needed.

**Comment by tomoam** [comment]
Related to this, in rare cases, there seems to be an error when moving from an exercise with `.env` file to one without `.env` file.


https://user-images.githubusercontent.com/29677552/231753951-49ac5ad7-7b42-4565-b75f-3ac933e796d6.mov
