### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Hugos68** [sveltejs/learn.svelte.dev#399]
When searching something at the top of the docs bar and no results are found it says:
![image](https://github.com/sveltejs/learn.svelte.dev/assets/63101006/6169f6bf-8382-40de-b060-66c118c17b04)
Which is a typo, it's probably supposed to say: "This query didn't produce any results... " or "This query produced no results..."

**Comment by giacomo-folli** [comment]
I think this issue should be closed.  It has been fixed.
<img width="386" alt="image" src="https://github.com/sveltejs/learn.svelte.dev/assets/119410424/2828b548-398e-4cff-b750-664bbc08f7ac">
