### ISSUE TITLE
learn.svelte.dev site consume too much memory on macOS

### ISSUE THREAD

**Issue by kresnasatya** [sveltejs/learn.svelte.dev#407]
Hi everyone! I try to learn Svelte and SvelteKit in learn.svelte.dev site. But, around 10 minutes my laptop is getting hot. I check the site consume more than 2GB memory. I'm using MacBook Air M1 with 8GB RAM.

I'm curious what are the problems that make this site consume too much memory.

Here's the screenshot that the site consume more RAM on macOS. I'm using Safari to access the site.

<img width="1440" alt="Screenshot 2023-06-25 at 20 20 50" src="https://github.com/sveltejs/learn.svelte.dev/assets/11099186/848cde97-a525-4ba1-9eb3-406c36c0b9ab">

I clone the site and run it locally but the result still same.

<img width="1440" alt="Screenshot 2023-06-26 at 06 20 53" src="https://github.com/sveltejs/learn.svelte.dev/assets/11099186/f9b43e6e-63cd-4ae4-a320-3edc6c240008">

The current solution is using the legacy tutorial from svelte.dev. But, I wish I can use learn.svelte.dev site as a place I learn Svelte and SvelteKit. 🥲

**Comment by Conduitry** [comment]
learn.svelte.dev is essentially running Node.js on a mini file system all in memory in your browser. Two gigabytes doesn't surprise me all that much, honestly. This would mostly be a question for StackBlitz (as we're using their Web Containers tech for learn.svelte.dev under the hood), but I don't know that there's much for them to do.

**Comment by kresnasatya** [comment]
Hi @Conduitry, I have make an issue in Web Container core repo and get the answer from Stackblitz team. They told me this issue (reducing memory) in their roadmap. I will close this issue. Thank you.
