### ISSUE TITLE
Svelte website keeps refreshing and crashes on iOS.

### ISSUE THREAD

**Issue by drnkwati** [sveltejs/learn.svelte.dev#416]
### Describe the bug

Hi.
Following the recent release and update of svelte, the website keeps refreshing and finally crashes when browsing on mobile devices. I am using mobile safari on IOS.

### Reproduction

https://learn.svelte.dev/tutorial/welcome-to-svelte

### System Info

```shell
Safari mobile IOS 16
```

### Severity

annoyance

**Comment by dummdidumm** [comment]
I don't see a refreshing happen before the crash. I believe there's some issue with Safari running out of memory of something, which is a known problem I believe (but not sure).

**Comment by drnkwati** [comment]
I tried testing on Firefox mobile for IOS and the problem persist. 
@dummdidumm The refreshing happens. If you do not see it, another developer will.
There is no memory problem. The problem only occurs in mobile browsers. 
Desktop browsers seem to work fine.

**Comment by snuffyDev** [comment]
Just chiming in with an additional screen recording, in case it’s of any use.

https://github.com/sveltejs/learn.svelte.dev/assets/72365477/40c1d87d-373e-4e84-a1a9-b8a8c29043aa

**Comment by snuffyDev** [comment]
> I don't see a refreshing happen before the crash. I believe there's some issue with Safari running out of memory of something, which is a known problem I believe (but not sure).

Seems as though this is right. 

https://github.com/sveltejs/learn.svelte.dev/assets/72365477/fb2612a4-712e-40d4-bdd5-c42d681bdaaa

![IMG_1792](https://github.com/sveltejs/learn.svelte.dev/assets/72365477/9f5cea7a-e55d-4d23-a83c-4fd585aede94)

**Comment by AchThomas** [comment]
Same problem as OP stated here on Chrome for iOS.

**Comment by beykansen** [comment]
I have same problem too

**Comment by drnkwati** [comment]
@benmccann If only you knew the number of iOS users you wouldn't be raising such suggesting.
You are suggesting that people should purchase android phones just to read the documentation. 🤣
That's a Nono suggestion 👎

**Comment by benmccann** [comment]
I'm quite aware iOS is highly used. But I don't see a solution to the problem. As best I can tell, iOS is killing processes to save memory, but we have limited options to reduce memory and no ability to stop iOS from doing what it's doing. It seems better to tell people to do the tutorial on their laptops/desktops than it is to crash. I'm aware it's not ideal, but it seems the least bad of the options available.

We can work on making the Svelte tutorials available using the standard REPL backend, which should hopefully work on iOS. For SvelteKit, which has a server-side portion, I simply don't see an alternative. Users on iOS can still read the documentation - it will only be the SvelteKit tutorial that is limited.

**Comment by kane81** [comment]
FYI Duplicate issue https://github.com/sveltejs/learn.svelte.dev/issues/493

**Comment by JPVan** [comment]
Would help with a pull request be welcome? As a temporary solution until Apple allows other browsers (maybe never) could this website do one or the other of these two options? 

- Check for iOS and not load a web container in that case (perhaps show static version of the docs)? 

- Or on all devices (or perhaps on devices using mobile layout) not load the web container (since it’s not needed yet) until the user selects Editor from the Tutorial / Editor switch? 

As far as I can tell, the content shown in the following screenshot does not require web containers. 
![IMG_7735](https://github.com/sveltejs/learn.svelte.dev/assets/11825317/1cfcd309-9f44-49d6-b49e-5e7f006b5474)

**Comment by JPVan** [comment]
Just now saw that the [Svelte 5 preview](https://svelte-5-preview.vercel.app/docs/introduction), for instance [the demo showing that rune objects and arrays are deeply reactive](https://svelte-5-preview.vercel.app/#H4sIAAAAAAAAE42QwWrDMBBEf2URhUhUNEl7c21DviPOwZY3jVpZEtIqUBz9e-UUt9BTj7M784bdmZ21wciq48xsPyGr2MF7Jhl9-kXEKxrCoqNLQS2TOqqgPbWd7cgggU3TgCFCAw-RekJ-3Et4lvByEq-drbe_dlsPichZcFYZrT6amQto2pXw5FO88FUYtG90gUfYi3zvWrYL75vxL57zfA07_zfr23k1vjtt-aZ0bQTcbrDL5ZifZcAxKeS8lzDc8X0xDhJ2ItdbX1jlOZMb9VnjyCoKCfMpfwG975NFVwEAAA==) works fine on iOS. So if that will be moved to learn.svelte.dev likely in a couple of months, maybe it makes sense not putting more effort into Svelte 4 docs.

**Comment by eltigerchino** [comment]
I've submitted a PR to stop loading the app preview part for iOS devices. Before it gets merged, you can have a go at it here https://learn-svelte-dev-git-fix-ios-crash-svelte.vercel.app the code and guides are still readable

**Comment by JPVan** [comment]
Works great, thanks so much!
