### ISSUE TITLE
bug: 🐛 bind numeric inputs takes "e" as a valid input

### ISSUE THREAD

**Issue by SeyyedKhandon** [sveltejs/learn.svelte.dev#433]
I've been learning svelte through the great [learn.svelte.dev/numeric-inputs](https://learn.svelte.dev/tutorial/numeric-inputs), and when I was playing with number input binding, I found out that despite what the docs says:

> With bind:value, Svelte takes care of it for you

It actually takes `e` character which it shouldn't. 

![image](https://github.com/sveltejs/learn.svelte.dev/assets/59599950/36f175af-a118-4e9f-a3d9-a4ba930b027c)

I've tried to track it inside of the svelte core, but couldnt make it.

![image](https://github.com/sveltejs/learn.svelte.dev/assets/59599950/dfe5d14e-2379-448b-874c-988d4cf9c09e)

And also wonder what is this `dirty`?

![image](https://github.com/sveltejs/learn.svelte.dev/assets/59599950/25db6a7f-0964-452c-a9d2-ebedad075e63)

I really want to contribute to svelte to make it better cause I love this. I would appreciate if you tell me how to...

**Comment by SeyyedKhandon** [comment]
Submitted the complete version in svelte core GitHub due it seems more related to that place
https://github.com/sveltejs/svelte/issues/8985

**Comment by geoffrich** [comment]
Closing in favor of the linked Svelte issue.
