### ISSUE TITLE
Left click to create folder or file UI is not user friendly

### ISSUE THREAD

**Issue by Dave-lab12** [sveltejs/learn.svelte.dev#439]
### When I left-click to create a new file or folder, the background is transparent and not user friendly. 
![image](https://github.com/sveltejs/learn.svelte.dev/assets/56738450/8057f264-6c73-4a5e-bd4a-3adca8fbf827)
![image](https://github.com/sveltejs/learn.svelte.dev/assets/56738450/d7cb1863-1b1d-40fe-8ae0-8d7d64d2a0ed)

### Contribution
-  I can create a pull request to fix the problem

**Comment by dummdidumm** [comment]
PR welcome!
