### ISSUE TITLE
cannot find package 'esbuild'

### ISSUE THREAD

**Issue by anrizal** [sveltejs/learn.svelte.dev#449]
Hello all,

I tried to run "node scripts/create-common-bundle" as per README but I encountered the following issue.

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'esbuild' imported from /home/rizal/learn.svelte.dev/scripts/create-common-bundle/index.js

any idea on how to proceed ?

**Comment by Conduitry** [comment]
You need to install the project's dependencies first with pnpm.
