### ISSUE TITLE
`<button>` is missing styles

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/learn.svelte.dev#454]
there's a button here, but you can't see it 

<img width="569" alt="image" src="https://github.com/sveltejs/learn.svelte.dev/assets/1162160/b763d6bc-53ca-4c90-9b4c-c64d0d92326b">

**Comment by commitsovercoffee** [comment]
Can I make a PR for this ?

This is the current behaviour on [learn.svelte.dev](https://learn.svelte.dev/tutorial/welcome-to-svelte) right now.
|      Light Mode      |      Dark Mode      |
| :---------------------: | :---------------------: |
| ![live_light](https://github.com/sveltejs/learn.svelte.dev/assets/129554482/5112ae0f-9e68-4f75-8ea6-dd4a40bfce4d) | ![live_dark](https://github.com/sveltejs/learn.svelte.dev/assets/129554482/6bce1a1c-4872-4726-a92c-1f51706f77f5) |

I made below changes to `/src/routes/tutorial/[slug]/Sidebar.svelte`  to add some style.

```diff
	.modal-contents button {
		display: block;
-		background: var(--prime);
+		background: var(--sk-theme-1);
		color: white;
		padding: 1rem;
		width: 10em;
		margin: 1em 0 0 0;
		border-radius: var(--sk-border-radius);
		line-height: 1;
+		transition:all 0.2s;
+	}
+
+	.modal-contents button:hover {
+		box-shadow: 2px 6px 20px rgba(0, 0, 0, 0.35);
	}
```

Does this look good ? (click on GIF to expand)

|      Light Mode      |      Dark Mode      |
| :---------------------: | :---------------------: |
|![light](https://github.com/sveltejs/learn.svelte.dev/assets/129554482/edaa213d-cb7b-4157-b533-43e2e04e9f51)|![dark](https://github.com/sveltejs/learn.svelte.dev/assets/129554482/601b59ba-2c23-4c37-bdf5-49d9dce01208)|
