### ISSUE TITLE
Wrong file extension in 01-page-options

### ISSUE THREAD

**Issue by Pbotsaris** [sveltejs/learn.svelte.dev#455]
Hello friends!

In the the [01-page-options](https://github.com/sveltejs/learn.svelte.dev/tree/main/content/tutorial/04-advanced-sveltekit/02-page-options/01-page-options) page

>In the chapter on [loading data](https://github.com/sveltejs/learn.svelte.dev/blob/main/tutorial/page-data), we saw how you can export load functions from `+page.js`, `+page.server.js`, `+layout.js` and `+layout.server.js` files. We can also export various page options from these modules (...)

`+page.js` and `+layout.js` have the wrong file extension. It should be `+page.svelte` and `+layout.svelte` respectively, no?

**Comment by geoffrich** [comment]
No, load functions aren't exported from `+page.svelte` files. They are exported from `+page.js` or `+layout.js` files (where they are called "universal" load functions) or from `+page.server.js` or `+layout.server.js` files (where they are called "server" load functions). See the docs: https://kit.svelte.dev/docs/load#universal-vs-server
