### ISSUE TITLE
Navbar Scroll Effects tutorial is not working

### ISSUE THREAD

**Issue by legionaryu** [sveltejs/learn.svelte.dev#498]
As soon as the tutorial page (https://svelte.dev/repl/335bdb2084ae4331bf0070d40ae36f47?version=3.29.4) is open, the following error shows up:
"cubicInOut" is not exported by "https://unpkg.com/svelte@3.29.4/easing/index.js", imported by "https://unpkg.com/svelte@3.29.4/transition/index.mjs".

And the page result is empty.
I'm using Firefox 117.0 (64-bit).

Logs: 
Error: "cubicInOut" is not exported by "https://unpkg.com/svelte@3.29.4/easing/index.js", imported by "https://unpkg.com/svelte@3.29.4/transition/index.mjs".
    Immutable 14
        T
        error
        traceVariable
        findVariable
        findVariable
        bind
        bind
        bind
        bind
        bind
        bind
        bindReferences
        sortModules
        build
index-940bbb7d.js:64:4853
    Rg Immutable

**Comment by Conduitry** [comment]
What tutorial page is that? That doesn't appear to be any code on learn.svelte.dev or in the old svelte.dev tutorial.

**Comment by legionaryu** [comment]
I thought it was an official tutorial, now I see that it's a repl from
someone else that was highly ranked by Google.

I'm going to close this issue.

Em qua., 6 de set. de 2023 22:41, Conduitry ***@***.***>
escreveu:
