### ISSUE TITLE
Create a youtube channel with courses and updates about svelte and sveltekit

### ISSUE THREAD

**Issue by H1Mohamed** [sveltejs/learn.svelte.dev#510]
I'm new to svelte Kit and its very hard for me to find legitimate YouTube tutorial that are beginner friendly, show every step of the way.
that really are amusing to watch and they're up to date, you might say there is the website's tutorial, but I prefer video type content than written type content, well I dont want other beginners new to web dev suffer as me, so this could be a very good idea.

**Comment by geoffrich** [comment]
This isn't something the maintainer team is going to take on. Text-based documentation and tutorials are much easier for us to keep up-to-date than recording video. There are quite a few Svelte/SvelteKit-focused YouTube channels if you prefer learning via video.
