### ISSUE TITLE
Advancing to the next lesson should scroll to the top

### ISSUE THREAD

**Issue by alex-k-exe** [sveltejs/learn.svelte.dev#528]
https://github.com/sveltejs/learn.svelte.dev/assets/101605664/c30f2845-0d6b-4c24-8074-f449fbf1e527

As shown in the video above, when you click for the next lesson the lesson panel retains its scroll position, which becomes very tedious after a few lessons.
This makes sense for when you click to move back a lesson but atleast in my opinion, it should instead scroll to the top when you advance to a new one

Thanks

**Comment by Rich-Harris** [comment]
thanks! closed by #530
