### ISSUE TITLE
Missing `bind:` in lesson 'Part 1 / Bindings / Select bindings'

### ISSUE THREAD

**Issue by App-rentice** [sveltejs/learn.svelte.dev#532]
In the [lesson](https://learn.svelte.dev/tutorial/select-bindings) about `Select bindings` there is missing a `bind:` on line 32.
Instead of `value={selected}` it should be `bind:value={selected}`.

At the bottom of the sample code is a paragraph which shows the current selected option-id, which wouldn't work as is.

**Comment by Conduitry** [comment]
The idea is that you need to complete the tutorials. This page purposefully contains an incomplete implementation, like all of the other pages in the tutorial.
