### ISSUE TITLE
bind: and on:click syntax improvments

### ISSUE THREAD

**Issue by JoeldelPilar** [sveltejs/learn.svelte.dev#535]
(I couldn't find any other issue that addresses this, sorry if i missed it!)

Would it be possible to add keyboard shortcuts for bind: and on:click?

bind: can be shortened to just : and on:click to just :click

When we work in web development, we are always (almost) creating forms, clicking events, etc. Having a shortcut to at least these two would be great!

**Comment by dummdidumm** [comment]
I don't fully understand - are you proposing a shortcut in the context of `learn.svelte.dev` that autocompletes to `bind:..` or `on:..`, or are you suggesting that the Svelte syntax itself is enhanced to allow these shortcuts?
The latter is not something we want to support - we read code far more often than we write it, and as such readability is more important than saving two keystrokes.

**Comment by JoeldelPilar** [comment]
The suggestion is to allow the usage of <code>:</code> when binding i.e a inputs value to a variable and for events allow <code>:click</code> (and other events). The idea comes from Vue.js where this is supported. I myself and other co-workers that work i Vue appreciates this way to work. The syntax, I belive, isen't hard to get used to. Isent it practical to allow similar funtionality across frameworks where it's possible? 

Anyway, its just a suggestion from someone coming from Vue 🙂

**Comment by dummdidumm** [comment]
Ok so it sounds like you are proposing the latter - a shortcut within Svelte itself. In that case I'm closing this as won't do for the reasons above. Thank you.
