### ISSUE TITLE
Supporting "Oxford" commas in the tutorial text

### ISSUE THREAD

**Issue by kshyun28** [sveltejs/learn.svelte.dev#549]
## Context
Hello, I've been learning frontend development through the wonderfully built Svelte tutorials. So far so good!

However, I've noticed commas are being left out before the `and` when mentioning lists.

Examples:
- Perhaps we want to make these boxes `red, green and blue`. [link](https://learn.svelte.dev/tutorial/component-styles)
- Every block-level element has `clientWidth, clientHeight, offsetWidth and offsetHeight bindings`. [link](https://learn.svelte.dev/tutorial/dimensions)

I've also been learning technical writing and have seen `Oxford commas` recommended in the [Google Technical Writing course](https://developers.google.com/tech-writing/one/punctuation).

With `Oxford commas`, the examples above would look like:
- red, green`,` and blue
- clientWidth, clientHeight, offsetWidth`,` and offsetHeight bindings

## Question
I know this is a matter of preference, so I was wondering if the team would like to adapt `Oxford commas` into the tutorial contents?

Either way I'm fine, but if the team would like to use `Oxford commas`, I'll be happy to help out with editing the content.

Cheers!

P.S. I have noticed that the content uses British English, where `Oxford commas` are not extensively used.

**Comment by dummdidumm** [comment]
I lean towards keeping it as is. It's done without the oxford comma everywhere in the docs across all sites, and changing it would take more work and change of habit than it's worth.

**Comment by kshyun28** [comment]
Got it. Agree that it doesn't really bring significant improvements to be worth the additional work. Didn't find it to be a huge issue while going through the tutorials anywa.

Thanks for clearing it up and will close this now.
