### ISSUE TITLE
How to open a pull request

### ISSUE THREAD

**Issue by joaopedrorc** [sveltejs/learn.svelte.dev#555]
I found some inconsistent grammar errors in the tutorial documentation and comments and I'd like to submit a 
pull request fixing those errors but I didn't find any docs explaining how to open pull requests. 

*My first contribution to Svelte community*.

**Comment by Conduitry** [comment]
You'd open it the same way you'd open any pull request, for example this one: https://github.com/ocean-ds/ocean-tokens/pull/284

**Comment by Rich-Harris** [comment]
For tutorial content specifically you can click the 'edit this page' link in the bottom left of each exercise

**Comment by joaopedrorc** [comment]
Thanks guys! @Rich-Harris @Conduitry

I've opened the PR: https://github.com/sveltejs/learn.svelte.dev/pull/556
