### ISSUE TITLE
[tutorial errata] just a few minor fixes that I noticed while reading

### ISSUE THREAD

**Issue by warren-bank** [sveltejs/learn.svelte.dev#571]
never mind.. sorry

**Comment by Conduitry** [comment]
I don't know that these sorts of things belong at this point in the tutorial. To answer some of these specific points: It's only equivalent to `name.update(n => n + '!')` if your store also implements the `.update()` method. The stores created by the exports from `svelte/store` so, but this is not guaranteed by the store contract. `$name += '!'` compiles to `name.set($name + '!')` which is guaranteed to work for all stores that satisfy the contract.

`$name` does not have special meaning when it's been shadowed by a local variable like a function parameter.

`.set` might be microscopically faster, but I don't think it would make any difference in the context of a real application.

**Comment by warren-bank** [comment]
3. Part 3 / Routing / Pages
   * [tutorial](https://learn.svelte.dev/tutorial/pages)
   * git:
     1. [`on:change`](https://github.com/sveltejs/learn.svelte.dev/blob/main/src/routes/tutorial/%5Bslug%5D/Output.svelte#L129)
     2. [`function set_iframe_src(src)`](https://github.com/sveltejs/learn.svelte.dev/blob/main/src/routes/tutorial/%5Bslug%5D/Output.svelte#L85-L105)
   * comments:
     - the _theme_ configured for the tutorial is always used by the sample app that is rendered in an iframe
     - the tutorial allows the user to specify the relative URL (ie: route) that is rendered by the app
     - this relative URL should allow the user to override the global theme by specifying a `?theme=` querystring parameter
       * ex: `/about?theme=dark`
     - however, this querystring value is updated by `set_iframe_src` immediately before the iframe is rendered
   * suggestion:
     ```javascript
       /** @param {string} src */
       function set_iframe_src(src) {
         if (!iframe) return; // HMR

         // To prevent iframe flickering.
         // Set to `visible` by calling `set_iframe_visible` function
         // from iframe on:load or setTimeout
         iframe.style.visibility = 'hidden';
         setTimeout(set_iframe_visible, 1000);

         // removing the iframe from the document allows us to
         // change the src without adding a history entry, which
         // would make back/forward traversal very annoying
         const parentNode = /** @type {HTMLElement} */ (iframe.parentNode);
         parentNode?.removeChild(iframe);

         const url = new URL(src);

         if (!url.searchParams.has('theme'))
           url.searchParams.set('theme', $theme.current);

         iframe.src = url.href;
         parentNode?.appendChild(iframe);
       }
     ```
   * where:
     - the only change is the addition of a conditional test:<br>&nbsp;&nbsp;`if (!url.searchParams.has('theme'))`<br>before updating the _theme_ querystring parameter

**Comment by warren-bank** [comment]
4. Part 3 / Shared modules / The `$lib` alias
   * [tutorial](https://learn.svelte.dev/tutorial/lib)
   * [git](https://github.com/sveltejs/learn.svelte.dev/blob/main/content/tutorial/03-sveltekit/05-shared-modules/01-lib/app-a/src/routes/a/deeply/nested/route/%2Bpage.svelte)
   * bug:
     - the following line:
       ```javascript
         import { message } from '../../../../../../lib/message.js';
       ```
     - should be:
       ```javascript
         import { message } from '../../../../../lib/message.js';
       ```
   * comments:
     - remove one instance of: `../`
     - as is:
       ```text
         500
         Internal Error
         Failed to resolve import
       ```

**Comment by warren-bank** [comment]
note (to self):

5. Part 3 / Forms / Validation
   * [tutorial]()
   * comments:
     - `+page.server.js`
       ```javascript
         export const actions = {
           create: async ({ cookies, request }) => {
             return {success: 'saved OK'}
           },
           delete: async ({ cookies, request }) => {
             return {success: 'removed OK'}
           }
         }
       ```
     - `+page.svelte`
       ```text
         <script>
           export let form;
         </script>

         {#if form?.success}
           <p class="error">{form.success}</p>
         {/if}
       ```

**Comment by warren-bank** [comment]
note (to self):

6. Part 3 / Forms / Customizing `use:enhance`
   * [tutorial](https://learn.svelte.dev/tutorial/customizing-use-enhance)
   * comments:
     - `+page.server.js`
       ```javascript
         import {fail} from '@sveltejs/kit'

         export const actions = {
           delete: async () => {
             await new Promise((fulfil) => setTimeout(fulfil, 1000))

             return fail(500, {
               error: 'Database Error'
             })
           }
         }
       ```

**Comment by warren-bank** [comment]
note (to self):

7. Part 3 / Stores / page
   * [tutorial](https://learn.svelte.dev/tutorial/page-store)
   * comments:
     - `src/routes/+layout.svelte`
       ```text
         <script>
           import { page } from '$app/stores';

           const nav = [{
             name: 'home',
             path: '/'
           },{
             name: 'about',
             path: '/about'
           }]
         </script>

         <nav>
           {#each nav as item}
             <a href="{item.path}" aria-current={$page.url.pathname === item.path}>
               {item.name}
             </a>
           {/each}
         </nav>

         <slot />
       ```

**Comment by warren-bank** [comment]
note (to self):

8. Part 3 / Stores / navigating
   * [tutorial](https://learn.svelte.dev/tutorial/navigating-store)
   * comments:
     - `src/routes/+layout.svelte`
       ```text
         <script>
           import { page, navigating } from '$app/stores';

           $: console.log( JSON.stringify($navigating, null, 2) );
         </script>
       ```

**Comment by warren-bank** [comment]
note (to self):

9. Part 4 / Hooks / `handle`
   * [tutorial](https://learn.svelte.dev/tutorial/handle)
   * comments:
     - `src/hooks.server.js`
       ```javascript
         import { redirect } from '@sveltejs/kit';

         export async function handle({ event, resolve }) {
           console.log( JSON.stringify(event, null, 2) );

           switch(event.url.pathname) {
             case '/ping':
               throw redirect(307, '/pong')

             case '/pong':
               return new Response('pong')
           }

           return await resolve(event)
         }
       ```

**Comment by warren-bank** [comment]
note (to self):

9. Part 4 / Hooks / `handleFetch`
   * [tutorial](https://learn.svelte.dev/tutorial/handlefetch)
   * comments:
     - `src/hooks.server.js`
       ```javascript
         export async function handleFetch({ event, request, fetch }) {

           console.log('1. ' + (typeof event.request     === typeof request))
           console.log('2. ' + (typeof event.fetch       === typeof fetch))
           console.log('3. ' + (typeof event.request.url === typeof request.url))

           console.log('4. ' + (event.request     === request))
           console.log('5. ' + (event.fetch       === fetch))
           console.log('6. ' + (event.request.url === request.url))

           console.log('7. typeof event.url   => ' + (typeof event.url)   + ((event.url   instanceof URL) ? ' (instanceof URL)' : ''))
           console.log('8. typeof request.url => ' + (typeof request.url) + ((request.url instanceof URL) ? ' (instanceof URL)' : ''))

           return await fetch(request);
         }
       ```
     - logs:
       ```text
         1. true
         2. true
         3. true
         4. false
         5. false
         6. false
         7. typeof event.url   => object (instanceof URL)
         8. typeof request.url => string
       ```

**Comment by warren-bank** [comment]
note (to self):

11. Part 4 / Page options / `trailingSlash`
   * [tutorial](https://learn.svelte.dev/tutorial/trailingslash)
   * comments:
     - `src/routes/+layout.svelte`
       ```text
         <nav>
           <a href="/always">/always</a>
           <a href="/always/">/always/</a>
           <a href="/ignore">/ignore</a>
           <a href="/ignore/">/ignore/</a>
           <a href="/never">/never</a>
           <a href="/never/">/never/</a>
         </nav>

         <slot />

         <hr />
         <h3>themes:</h3>
         <ul>
           <li><a href="./?theme=dark">dark</a></li>
           <li><a href="./?theme=light">light</a></li>
         </ul>
       ```

**Comment by warren-bank** [comment]
12. Part 4 / Advanced routing / Breaking out of layouts
   * [tutorial](https://learn.svelte.dev/tutorial/breaking-out-of-layouts)
   * example given:
     - `src/routes/a/b/c/+page@.svelte`
       * uses:
         - `src/routes/+layout.svelte`
       * ignores:
         - `src/routes/a/b/c/+layout.svelte`
  * comments:
    - the individual page resets its layout hierarchy to the root layout
    - should it not then also inherit the layout in its own directory?
  * questions:
    - can a layout hierarchy be reset for all descendent pages?
      * example:
        - `src/routes/a/b/c/+layout@.svelte`
        - `src/routes/a/b/c/+page.svelte`
          * such that it uses:
            - `src/routes/+layout.svelte`
            - `src/routes/a/b/c/+layout@.svelte`
        - `src/routes/a/b/c/d/+layout.svelte`
        - `src/routes/a/b/c/d/+page.svelte`
          * such that it uses:
            - `src/routes/+layout.svelte`
            - `src/routes/a/b/c/+layout@.svelte`
            - `src/routes/a/b/c/d/+layout.svelte`

**Comment by warren-bank** [comment]
1. Docs: CORE CONCEPTS / Loading data / Using parent data
   * [docs](https://kit.svelte.dev/docs/load#using-parent-data)
   * [git](https://github.com/sveltejs/kit/blob/%40sveltejs/kit%402.5.0/documentation/docs/20-core-concepts/20-load.md?plain=1#L382-L397)
   * comments:
     - fair warning&hellip; to avoid waterfalls
     - the given implementation does _not_ do that
       * 2 Promises are resolved synchronously
       * the order doesn't matter
     - a better implementation might more closely resemble:
       ```javascript
         export async function load({ params, parent }) {
           const [parentData, data] = await Promise.all([
             parent(),
             getData(params)
           ]);

           return {
             ...data
             meta: { ...parentData.meta, ...data.meta }
           };
         }
       ```

**Comment by warren-bank** [comment]
note (to self):

13. Part 4 / Environment variables / `$env/static/private`
   * [tutorial](https://learn.svelte.dev/tutorial/env-static-private)
   * comments:
     - `src/routes/+page.server.js`
       ```javascript
         import * as env from '$env/static/private';

         console.log(JSON.stringify(env, null, 2));
       ```
