### ISSUE TITLE
Instructions for allowing 3P cookies

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/learn.svelte.dev#60]
I've been bitten by this multiple times — we need to teach people how to allow third party cookies if stuff doesn't work (see also: #59)

**Comment by Mlocik97** [comment]
instead of using 3P cookies, can't we host containers itself on same domain? It can still be on sb's servers, but somewhat redirect or resp. configure DNS so those containers are on same domain, and we don't need to solve 3P cookies.
