### ISSUE TITLE
Dev server won't start

### ISSUE THREAD

**Issue by boro28** [sveltejs/learn.svelte.dev#606]
Going to the [svelte tutorial](https://learn.svelte.dev/tutorial/welcome-to-svelte) svelte preview won't start and hangs on  "starting dev server"  at 80%. Console don't show any errors. Tested on multiple machines, browsers and networks.

**Comment by Rich-Harris** [comment]
This turned out to be an issue with a recent update to WebContainers — the update has been reverted while a fix is investigated, so I'll close this. Thanks for flagging
