### ISSUE TITLE
error in tutorial/await-blocks

### ISSUE THREAD

**Issue by moonhuntercode** [sveltejs/learn.svelte.dev#616]
unexpected response in :
Request failed message  in https://learn.svelte.dev/tutorial/await-blocksunexpected response in
![Screenshot 2024-05-18 140632](https://github.com/sveltejs/learn.svelte.dev/assets/53928868/5c5adfce-c904-4ed3-82d3-aa25cbcd5878)

**Comment by Conduitry** [comment]
https://github.com/sveltejs/learn.svelte.dev/blob/main/content/tutorial/01-svelte/04-logic/06-await-blocks/app-a/src/routes/random-number/%2Bserver.js

This is intended. The endpoint fails 1/3 of the time so we can demonstrate `{:catch}`.
