### ISSUE TITLE
Webcontainers

### ISSUE THREAD

**Issue by TheHamkerCat** [sveltejs/learn.svelte.dev#99]
Webcontainer stuff doesn't work even after disabling Firefox's "Enhanced tracking protection"

![image](https://user-images.githubusercontent.com/58004714/192499328-e66c3c91-bd37-4a17-8906-96ac1ff61565.png)

It also says "You may need to enable third party cookies".
I searched everywhere, couldn't find an option to disable that.

**Comment by dummdidumm** [comment]
The error message sais that it timed out, it may just have taken too long (happened to me, too, on first try).

**Comment by TheHamkerCat** [comment]
> The error message sais that it timed out, it may just have taken too long (happened to me, too, on first try). What happens if your reload the page after this error message?

tried reloading several times, doesn't make a difference

**Comment by JoshAtticus** [comment]
I am also having this same issue, tested on Google Chrome, Vivaldi, Firefox, all using Linux & ChromeOS

**Comment by JoshAtticus** [comment]
Looking in the console, it seems to be an HTTP 403 forbidden error when accessing the js files required to run it.

**Comment by neznayer** [comment]
Same here.
Lessons works until this one
 https://learn.svelte.dev/tutorial/reactive-assignments
are working fine. 

Chrome v.106

**Comment by Rich-Harris** [comment]
There have been a lot of changes to the WebContainer integration since this issue was opened, and a lot of stuff has been fixed, so I'm going to be optimistic and close this issue as it's much more reliable these days 🤞
